const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
html=html.replaceAll('Instalaciones eléctricas y energía solar en Palma de Mallorca','Instalaciones eléctricas y energía solar en Mallorca')
 .replace('Electricidad y energía solar en Palma de Mallorca','Electricidad y energía solar en Mallorca')
 .replace('en Palma de Mallorca<span class="orange">','en Mallorca<span class="orange">')
 .replace('POLINETIC · PALMA DE MALLORCA','POLINETIC · SERVICIO EN TODA MALLORCA')
 .replace('Polinetic en Palma de Mallorca: instalaciones y reparaciones eléctricas, energía solar y mantenimiento de comunidades. Consulta tu proyecto en el 655 143 119.','Instalaciones eléctricas y energía solar en toda Mallorca. Polinetic: reparaciones y mantenimiento de comunidades, con base en Palma. Llama al 655 143 119.')
 .replace('Indica dónde necesitas el trabajo y valoramos contigo las opciones.','Atendemos toda Mallorca: indica dónde necesitas el trabajo y valoramos contigo las opciones.')
 .replace('Usaremos tus datos para atender esta consulta.','Responsable: Polinetic, S.L. Usaremos tus datos para atender tu consulta y preparar el presupuesto solicitado.');
html=html.replace(/(<script type="application\/ld\+json">)(.*?)(<\/script>)/,(_,start,data,end)=>{
 const schema=JSON.parse(data);schema.legalName='Polinetic, S.L.';schema.areaServed={'@type':'Place',name:'Mallorca'};return start+JSON.stringify(schema)+end;
});
html=html.replace('<div class="faq-list reveal"><details>', '<div class="faq-list reveal"><details><summary>¿En qué zonas trabajáis?<span aria-hidden="true">+</span></summary><p>Atendemos toda Mallorca, con base en Palma. Indica la localidad y el tipo de trabajo al solicitar presupuesto para que podamos valorar tu caso.</p></details><details>');
fs.writeFileSync(path.join(root,'index.html'),html);
const shell=(title,body)=>`<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,follow"><title>${title} | Polinetic</title><link rel="icon" href="assets/brand/polinetic.png" type="image/png"><link rel="stylesheet" href="styles.css"></head>
<body><a class="skip-link" href="#contenido">Saltar al contenido</a><header class="header legal-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Polinetic, inicio"><img src="assets/brand/polinetic.png" width="595" height="219" alt="Polinetic. Servicios tecnológicos avanzados"></a><a class="text-link" href="index.html#contacto">Contacto ↗</a></div></header>
<main class="container legal-page" id="contenido"><p class="eyebrow">POLINETIC, S.L.</p><h1>${title}</h1>${body}<p><a href="index.html">Volver a la web</a></p></main><footer class="footer"><div class="container footer-bottom"><span>© 2026 Polinetic, S.L.</span><nav class="legal-links" aria-label="Información legal"><a href="aviso-legal.html">Aviso legal</a><a href="privacidad.html">Privacidad</a></nav></div></footer></body></html>`;
fs.writeFileSync(path.join(root,'aviso-legal.html'),shell('Aviso legal',`
<h2>Identificación y contacto</h2>
<dl><dt>Titular</dt><dd>Polinetic, S.L.</dd><dt>NIF</dt><dd>B57287922</dd><dt>Dirección de contacto</dt><dd>Carretera Militar, 219 A - Casa A<br>07600 Palma de Mallorca, Islas Baleares, España</dd><dt>Email</dt><dd><a href="mailto:servicios@polinetic.es">servicios@polinetic.es</a></dd><dt>Teléfono</dt><dd><a href="tel:+34655143119">655 143 119</a></dd><dt>Sitio web</dt><dd>https://polinetic.es</dd></dl>
<h2>Objeto del sitio</h2><p>Esta web presenta los servicios de instalaciones y reparaciones eléctricas, instalaciones fotovoltaicas, mantenimiento de comunidades, asesoramiento energético y venta de material eléctrico de Polinetic en Mallorca.</p><p>La información es orientativa. El alcance, disponibilidad, precio y condiciones de cada trabajo se concretan en el presupuesto y, en su caso, en el acuerdo con el cliente. Enviar una consulta no implica contratar un servicio ni aceptar un presupuesto.</p>
<h2>Uso de la web</h2><p>El visitante debe utilizar la web de forma lícita y proporcionar datos veraces al contactar. No está permitido emplear el formulario para comunicaciones abusivas, suplantaciones o contenidos que perjudiquen a terceros.</p>
<h2>Contenidos e imágenes</h2><p>El nombre y logotipo de Polinetic, así como los demás contenidos, están sujetos a los derechos de sus titulares. Las fotografías de archivo son ilustrativas de los servicios y no se presentan como instalaciones realizadas por Polinetic. Su procedencia y licencia pueden consultarse en «Créditos de imágenes» al pie de la página principal.</p>
<h2>Disponibilidad y enlaces</h2><p>Polinetic procura mantener la información actualizada y el sitio disponible. Si detectas un error o una dificultad de acceso, comunícalo por email o teléfono. Los enlaces externos llevan a sitios gestionados por sus respectivos titulares.</p>
<h2>Datos personales</h2><p>El tratamiento de los datos de contacto se describe en la <a href="privacidad.html">política de privacidad</a>.</p>
<h2>Normativa aplicable</h2><p>Se aplica la legislación española y europea que corresponda. Los derechos de las personas consumidoras y las reglas imperativas sobre competencia judicial prevalecen en todo caso.</p>`));
fs.writeFileSync(path.join(root,'privacidad.html'),shell('Política de privacidad',`
<p>Esta información explica cómo se tratan los datos facilitados al contactar con Polinetic a través de esta web, por email o por teléfono.</p>
<h2>Responsable</h2><p>Polinetic, S.L., NIF B57287922. Dirección de contacto: Carretera Militar, 219 A - Casa A, 07600 Palma de Mallorca, Islas Baleares. Email: <a href="mailto:servicios@polinetic.es">servicios@polinetic.es</a>. Teléfono: <a href="tel:+34655143119">655 143 119</a>.</p>
<h2>Datos, finalidad y base jurídica</h2><p>Al usar el formulario facilitas tu nombre, email, servicio de interés y el contenido de tu consulta. Se utilizan para responder, valorar el trabajo y preparar el presupuesto que solicites. El tratamiento de una solicitud de servicio se basa en las medidas precontractuales que pides, conforme al artículo 6.1.b del RGPD. Para comunicaciones generales, la base es el interés legítimo en atender las comunicaciones dirigidas a la empresa, conforme al artículo 6.1.f.</p><p>Los campos obligatorios permiten identificar y responder a tu solicitud. Si no los facilitas, no podremos tramitar el formulario; puedes utilizar el teléfono. Evita incluir datos sensibles o información de terceros que no sea necesaria. No utilizamos estas consultas para suscribirte a publicidad ni para decisiones automatizadas.</p>
<h2>Cómo se envía la consulta</h2><p>Cuando el envío directo está disponible, la web remite el mensaje al correo de Polinetic. Si se ofrece «Preparar email», se abre tu aplicación de correo y el envío solo se completa cuando lo confirmas allí. La web no guarda las consultas en una base de datos propia; el mensaje se conserva en el correo de la empresa según la finalidad y los plazos indicados a continuación.</p>
<h2>Conservación</h2><p>Los datos de la consulta se conservan durante el tiempo necesario para atenderla y realizar el seguimiento del presupuesto. Si se contrata un servicio, se incorporarán a la relación con el cliente y se conservarán conforme a las obligaciones legales aplicables. Cuando dejen de ser necesarios, se suprimirán o, cuando proceda, se mantendrán bloqueados durante los plazos de responsabilidad legal.</p>
<h2>Destinatarios y proveedores</h2><p>Las consultas son atendidas por Polinetic. Los proveedores de alojamiento y correo pueden tratar los datos para prestar esos servicios por cuenta de la empresa, conforme a los acuerdos y garantías aplicables. Los datos no se venden y solo se comunicarán a otros destinatarios cuando exista una obligación legal o sea necesario para tramitar el servicio solicitado, informándote cuando corresponda.</p>
<h2>Seguridad y registros técnicos</h2><p>El formulario utiliza un contador temporal para limitar envíos abusivos. Se guarda una huella de la dirección IP, sin incluir el mensaje, con una ventana de 15 minutos; los ficheros caducados se eliminan al procesar nuevas consultas. El alojamiento puede generar registros técnicos de acceso y seguridad. La protección del formulario se basa en el interés legítimo en preservar la seguridad y disponibilidad del servicio.</p>
<h2>Tus derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad, cuando sean aplicables, escribiendo a <a href="mailto:servicios@polinetic.es">servicios@polinetic.es</a>. Indica el derecho que deseas ejercer y los datos necesarios para localizar tu consulta. Si hay dudas razonables sobre tu identidad, se podrá solicitar información adicional proporcionada para verificarla.</p><p>También puedes reclamar ante la <a href="https://www.aepd.es/">Agencia Española de Protección de Datos</a> si consideras que el tratamiento vulnera tus derechos.</p>
<h2>Cookies y servicios externos</h2><p>Esta versión de la web no incorpora cookies, herramientas de analítica, píxeles publicitarios ni mapas o reseñas incrustados. Las fuentes y fotografías se cargan desde el propio alojamiento. Al abrir un enlace externo se aplican las condiciones y la política de privacidad del sitio de destino.</p>`));
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nDisallow: /contact.php\nDisallow: /contact-config.php\nSitemap: https://polinetic.es/sitemap.xml\n');
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://polinetic.es/</loc></url></urlset>\n');
